# Generated by Django 5.1.dev20240204083941 on 2024-07-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name_plural': 'Favorites'},
        ),
    ]
