# Generated by Django 5.1.dev20240204083941 on 2024-08-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_favorites_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='movie_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favorites',
            name='tv_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='movie_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='tv_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
